### ISSUE TITLE
One loader, multiple loaders' mods

### ISSUE THREAD

**Issue by sschr15** [MOD-Magazine/MOD-Magazine#10] opened 2023-04-08 13:46 UTC

**Comment by HyperSoop** [comment] 2023-05-17 11:12
isn't this a duplicate of #1? thinkity think think

**Comment by Jamalam360** [comment] 2024-06-09 09:57
Closing this, feel free to reopen if interested in continuing writing (see Discord).

**Closed by Jamalam360** 2024-06-09 09:57 UTC
Labels: technical, future
